// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      title: {
        fontSize: 25,
        marginBottom: 5
      },
      subtitle: {
        fontSize: 22,
        marginBottom: 5
      },
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      }
    });

function SignInScreen(Props) {
  var navigation = Props.navigation;
  var _signInAsync = function (param) {
    return ReactNative.AsyncStorage.setItem("userToken", "abc").then((function (_result) {
                  return Promise.resolve((navigation.navigate("App"), /* () */0));
                }));
  };
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  style: styles.title,
                  children: "Cadastro"
                }), React.createElement(ReactNative.Text, {
                  style: styles.subtitle,
                  children: "Cadastrar meus dados"
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      _signInAsync(/* () */0);
                      return /* () */0;
                    }),
                  title: "Cadastrar"
                }));
}

SignInScreen.navigationOptions = {
  title: "Please sign in"
};

var make = SignInScreen;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
