// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as SignInScreen from "../screen/SignInScreen.bs.js";
import * as ReactNavigationStack from "react-navigation-stack";

var routes = {
  SignIn: SignInScreen.make
};

var $$navigator = ReactNavigationStack.createStackNavigator(routes, {
      mode: "modal",
      headerMode: "none"
    });

$$navigator.navigationOptions = {
  tabBarVisible: false
};

export {
  routes ,
  $$navigator ,
  
}
/* navigator Not a pure module */
