// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AppNavigator from "./navigation/AppNavigator.bs.js";

var app = AppNavigator.make;

export {
  app ,
  
}
/* AppNavigator Not a pure module */
