// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppStack from "./AppStack.bs.js";
import * as AuthStack from "./AuthStack.bs.js";
import * as ReactNavigation from "react-navigation";
import * as AuthLoadingScreen from "./AuthLoadingScreen.bs.js";
import * as AppContainer$ReactNavigation from "reason-react-navigation/src/AppContainer.bs.js";

var $$navigator = ReactNavigation.createSwitchNavigator({
      App: AppStack.$$navigator,
      Auth: AuthStack.$$navigator,
      AuthLoading: AuthLoadingScreen.make
    }, {
      initialRouteName: "AuthLoading"
    });

var AuthFlowAppContainer = AppContainer$ReactNavigation.Make({
      $$navigator: $$navigator
    });

function AppNavigator(Props) {
  var screenProps = {
    someProp: 42
  };
  return React.createElement(AuthFlowAppContainer.make, {
              screenProps: screenProps
            });
}

var make = AppNavigator;

export {
  AuthFlowAppContainer ,
  make ,
  
}
/* AuthFlowAppContainer Not a pure module */
