// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as HomeScreen from "./HomeScreen.bs.js";
import * as SettingScreen from "./SettingScreen.bs.js";
import * as ReactNavigationStack from "react-navigation-stack";

var routes = {
  Home: HomeScreen.make,
  Setting: SettingScreen.make
};

var $$navigator = ReactNavigationStack.createStackNavigator(routes, {
      mode: "modal",
      headerMode: "none"
    });

$$navigator.navigationOptions = {
  tabBarVisible: false
};

export {
  routes ,
  $$navigator ,
  
}
/* navigator Not a pure module */
