// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GlobalStyle from "./GlobalStyle.bs.js";
import * as ReactNative from "react-native";

function SignInScreen(Props) {
  var navigation = Props.navigation;
  var _signInAsync = function (param) {
    return ReactNative.AsyncStorage.setItem("userToken", "abc").then((function (_result) {
                  return Promise.resolve((navigation.navigate("App"), /* () */0));
                }));
  };
  return React.createElement(ReactNative.View, {
              style: GlobalStyle.styles.container,
              children: React.createElement(ReactNative.Button, {
                    onPress: (function (param) {
                        _signInAsync(/* () */0);
                        return /* () */0;
                      }),
                    title: "Sign in!"
                  })
            });
}

SignInScreen.navigationOptions = {
  title: "Please sign in"
};

var make = SignInScreen;

export {
  make ,
  
}
/*  Not a pure module */
